"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nubotddsmsg.sensor
  IDL file: nubotddsmsg.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import nubotddsmsg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class orientation(idl.IdlStruct, typename="nubotddsmsg.sensor.orientation"):
    x: types.float32
    y: types.float32
    z: types.float32
    w: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class angular_velocity(idl.IdlStruct, typename="nubotddsmsg.sensor.angular_velocity"):
    x: types.float32
    y: types.float32
    z: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class linear_acceleration(idl.IdlStruct, typename="nubotddsmsg.sensor.linear_acceleration"):
    x: types.float32
    y: types.float32
    z: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Magnetic(idl.IdlStruct, typename="nubotddsmsg.sensor.Magnetic"):
    x: types.float32
    y: types.float32
    z: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class euler_angles(idl.IdlStruct, typename="nubotddsmsg.sensor.euler_angles"):
    roll: types.float32
    pitch: types.float32
    yaw: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class imudata(idl.IdlStruct, typename="nubotddsmsg.sensor.imudata"):
    orientation: 'nubotddsmsg.sensor.orientation'
    angular_velocity: 'nubotddsmsg.sensor.angular_velocity'
    linear_acceleration: 'nubotddsmsg.sensor.linear_acceleration'
    Magnetic: 'nubotddsmsg.sensor.Magnetic'
    euler_angles: 'nubotddsmsg.sensor.euler_angles'


