"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nubotddsmsg.hr
  IDL file: nubotddsmsg.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import nubotddsmsg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class motorcmd(idl.IdlStruct, typename="nubotddsmsg.hr.motorcmd"):
    mode: types.uint8
    index: types.int32
    pos: types.float32
    vel: types.float32
    tau: types.float32
    kp: types.float32
    kd: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class motorcmds(idl.IdlStruct, typename="nubotddsmsg.hr.motorcmds"):
    level: types.uint8
    cmds: types.sequence['nubotddsmsg.hr.motorcmd']


@dataclass
@annotate.final
@annotate.autoid("sequential")
class motorstate(idl.IdlStruct, typename="nubotddsmsg.hr.motorstate"):
    mode: types.uint8
    index: types.int32
    pos: types.float32
    vel: types.float32
    cur: types.float32
    tau: types.float32
    tau_raw: types.float32
    error: types.int32
    tem: types.float32
    mos_tem: types.float32


@dataclass
@annotate.final
@annotate.autoid("sequential")
class motorstates(idl.IdlStruct, typename="nubotddsmsg.hr.motorstates"):
    level: types.uint8
    states: types.sequence['nubotddsmsg.hr.motorstate']


