"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: nubotddsmsg.hcmd
  IDL file: nubotddsmsg.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import nubotddsmsg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class hcmddata(idl.IdlStruct, typename="nubotddsmsg.hcmd.hcmddata"):
    vx: types.float32
    vy: types.float32
    omega: types.float32


