"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: nubotddsmsg.sensor
  IDL file: nubotddsmsg.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import nubotddsmsg


@dataclass
@annotate.final
@annotate.autoid("sequential")
class xxx(idl.IdlStruct, typename="nubotddsmsg.sensor.xxx"):
    mode: types.uint8
    pos: types.float32
    vel: types.float32
    tau: types.float32
    kp: types.float32
    kd: types.float32


